my_team_data = {'errors': [],
 'get': 'teams',
 'parameters': {'id': '29'},
 'response': [{'city': 'Dallas',
               'coach': 'Mike McCarthy',
               'code': 'DAL',
               'country': {'code': 'US',
                           'flag': 'https://media.api-sports.io/flags/us.svg',
                           'name': 'USA'},
               'established': 1960,
               'id': 29,
               'logo': 'https://media.api-sports.io/american-football/teams/29.png',
               'name': 'Dallas Cowboys',
               'owner': 'Jerry Jones',
               'stadium': 'AT&T Stadium'}],
 'results': 1}
my_league_data = {'errors': [],
 'get': 'leagues',
 'parameters': [],
 'response': [{'country': {'code': 'US',
                           'flag': 'https://media.api-sports.io/flags/us.svg',
                           'name': 'USA'},
               'league': {'id': 2,
                          'logo': 'https://media.api-sports.io/american-football/leagues/2.png',
                          'name': 'NCAA'},
               'seasons': [{'coverage': {'games': {'events': True,
                                                   'statisitcs': {'players': True,
                                                                  'teams': True}},
                                         'injuries': True,
                                         'players': True,
                                         'standings': True,
                                         'statistics': {'season': {'players': True}}},
                            'current': True,
                            'end': '2026-01-20',
                            'start': '2025-08-23',
                            'year': 2025},
                           {'coverage': {'games': {'events': True,
                                                   'statisitcs': {'players': True,
                                                                  'teams': True}},
                                         'injuries': False,
                                         'players': True,
                                         'standings': True,
                                         'statistics': {'season': {'players': True}}},
                            'current': False,
                            'end': '2025-01-21',
                            'start': '2024-08-24',
                            'year': 2024},
                           {'coverage': {'games': {'events': True,
                                                   'statisitcs': {'players': True,
                                                                  'teams': True}},
                                         'injuries': False,
                                         'players': True,
                                         'standings': True,
                                         'statistics': {'season': {'players': True}}},
                            'current': False,
                            'end': '2024-01-09',
                            'start': '2023-08-26',
                            'year': 2023},
                           {'coverage': {'games': {'events': True,
                                                   'statisitcs': {'players': True,
                                                                  'teams': True}},
                                         'injuries': False,
                                         'players': True,
                                         'standings': True,
                                         'statistics': {'season': {'players': True}}},
                            'current': False,
                            'end': '2023-01-10',
                            'start': '2022-08-27',
                            'year': 2022}]},
              {'country': {'code': 'US',
                           'flag': 'https://media.api-sports.io/flags/us.svg',
                           'name': 'USA'},
               'league': {'id': 1,
                          'logo': 'https://media.api-sports.io/american-football/leagues/1.png',
                          'name': 'NFL'},
               'seasons': [{'coverage': {'games': {'events': True,
                                                   'statisitcs': {'players': True,
                                                                  'teams': True}},
                                         'injuries': True,
                                         'players': True,
                                         'standings': True,
                                         'statistics': {'season': {'players': True}}},
                            'current': True,
                            'end': '2026-02-08',
                            'start': '2025-08-01',
                            'year': 2025},
                           {'coverage': {'games': {'events': True,
                                                   'statisitcs': {'players': True,
                                                                  'teams': True}},
                                         'injuries': False,
                                         'players': True,
                                         'standings': True,
                                         'statistics': {'season': {'players': True}}},
                            'current': False,
                            'end': '2025-02-09',
                            'start': '2024-08-02',
                            'year': 2024},
                           {'coverage': {'games': {'events': True,
                                                   'statisitcs': {'players': True,
                                                                  'teams': True}},
                                         'injuries': False,
                                         'players': True,
                                         'standings': True,
                                         'statistics': {'season': {'players': True}}},
                            'current': False,
                            'end': '2024-02-11',
                            'start': '2023-08-04',
                            'year': 2023},
                           {'coverage': {'games': {'events': True,
                                                   'statisitcs': {'players': True,
                                                                  'teams': True}},
                                         'injuries': False,
                                         'players': True,
                                         'standings': True,
                                         'statistics': {'season': {'players': True}}},
                            'current': False,
                            'end': '2023-02-12',
                            'start': '2022-08-05',
                            'year': 2022},
                           {'coverage': {'games': {'events': True,
                                                   'statisitcs': {'players': True,
                                                                  'teams': True}},
                                         'injuries': False,
                                         'players': True,
                                         'standings': True,
                                         'statistics': {'season': {'players': False}}},
                            'current': False,
                            'end': '2022-02-13',
                            'start': '2021-08-12',
                            'year': 2021},
                           {'coverage': {'games': {'events': True,
                                                   'statisitcs': {'players': True,
                                                                  'teams': True}},
                                         'injuries': False,
                                         'players': True,
                                         'standings': True,
                                         'statistics': {'season': {'players': False}}},
                            'current': False,
                            'end': '2021-02-07',
                            'start': '2020-09-13',
                            'year': 2020},
                           {'coverage': {'games': {'events': True,
                                                   'statisitcs': {'players': True,
                                                                  'teams': True}},
                                         'injuries': False,
                                         'players': True,
                                         'standings': True,
                                         'statistics': {'season': {'players': False}}},
                            'current': False,
                            'end': '2020-02-02',
                            'start': '2019-08-08',
                            'year': 2019},
                           {'coverage': {'games': {'events': True,
                                                   'statisitcs': {'players': True,
                                                                  'teams': True}},
                                         'injuries': False,
                                         'players': True,
                                         'standings': True,
                                         'statistics': {'season': {'players': False}}},
                            'current': False,
                            'end': '2019-02-03',
                            'start': '2018-08-09',
                            'year': 2018},
                           {'coverage': {'games': {'events': True,
                                                   'statisitcs': {'players': True,
                                                                  'teams': True}},
                                         'injuries': False,
                                         'players': True,
                                         'standings': True,
                                         'statistics': {'season': {'players': False}}},
                            'current': False,
                            'end': '2018-02-04',
                            'start': '2017-08-09',
                            'year': 2017},
                           {'coverage': {'games': {'events': True,
                                                   'statisitcs': {'players': True,
                                                                  'teams': True}},
                                         'injuries': False,
                                         'players': True,
                                         'standings': True,
                                         'statistics': {'season': {'players': False}}},
                            'current': False,
                            'end': '2017-02-05',
                            'start': '2016-08-12',
                            'year': 2016},
                           {'coverage': {'games': {'events': False,
                                                   'statisitcs': {'players': False,
                                                                  'teams': False}},
                                         'injuries': False,
                                         'players': False,
                                         'standings': True,
                                         'statistics': {'season': {'players': False}}},
                            'current': False,
                            'end': '2016-02-07',
                            'start': '2015-08-13',
                            'year': 2015},
                           {'coverage': {'games': {'events': False,
                                                   'statisitcs': {'players': False,
                                                                  'teams': False}},
                                         'injuries': False,
                                         'players': False,
                                         'standings': True,
                                         'statistics': {'season': {'players': False}}},
                            'current': False,
                            'end': '2015-02-01',
                            'start': '2014-08-07',
                            'year': 2014},
                           {'coverage': {'games': {'events': False,
                                                   'statisitcs': {'players': False,
                                                                  'teams': False}},
                                         'injuries': False,
                                         'players': False,
                                         'standings': True,
                                         'statistics': {'season': {'players': False}}},
                            'current': False,
                            'end': '2014-02-02',
                            'start': '2013-08-08',
                            'year': 2013},
                           {'coverage': {'games': {'events': False,
                                                   'statisitcs': {'players': False,
                                                                  'teams': False}},
                                         'injuries': False,
                                         'players': False,
                                         'standings': True,
                                         'statistics': {'season': {'players': False}}},
                            'current': False,
                            'end': '2013-02-03',
                            'start': '2012-08-09',
                            'year': 2012},
                           {'coverage': {'games': {'events': False,
                                                   'statisitcs': {'players': False,
                                                                  'teams': False}},
                                         'injuries': False,
                                         'players': False,
                                         'standings': True,
                                         'statistics': {'season': {'players': False}}},
                            'current': False,
                            'end': '2012-02-05',
                            'start': '2011-08-12',
                            'year': 2011},
                           {'coverage': {'games': {'events': False,
                                                   'statisitcs': {'players': False,
                                                                  'teams': False}},
                                         'injuries': False,
                                         'players': False,
                                         'standings': True,
                                         'statistics': {'season': {'players': False}}},
                            'current': False,
                            'end': '2011-02-06',
                            'start': '2010-08-12',
                            'year': 2010}]}],
 'results': 2}
